image: python:3.10.4

services:
  - postgres:latest
variables:
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

cache:
  paths:
    - ~/.cache/pip/

stages:
  - test

test:
  only:
    - master
  stage: test
  before_script:
    - echo "DB_NAME=$POSTGRES_DB" > .env
    - echo "DB_HOST=$POSTGRES_HOST" >> .env
    - echo "DB_USER=$POSTGRES_USER" >> .env
    - echo "DB_PWD=$POSTGRES_PASSWORD" >> .env
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - flake8
  - python3 manage.py test

