# Generated by Django 4.2.1 on 2023-05-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tesla_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tesla_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
