# Generated by Django 4.2.1 on 2023-05-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_tesla_access_token_user_tesla_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
