# Generated by Django 4.2.1 on 2023-05-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
