# Generated by Django 4.2.1 on 2023-05-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_spotify_access_token_user_spotify_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spotify_access_token',
            field=models.CharField(blank=True, max_length=2055, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='spotify_refresh_token',
            field=models.CharField(blank=True, max_length=2055, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tesla_access_token',
            field=models.CharField(blank=True, max_length=2055, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tesla_refresh_token',
            field=models.CharField(blank=True, max_length=2055, null=True),
        ),
    ]
