# Generated by Django 4.2.1 on 2023-05-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_spotify_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='spotify_id',
        ),
    ]
