# Generated by Django 4.2.1 on 2023-05-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
