# Generated by Django 3.2 on 2023-06-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('trial', 'Trial'), ('paid', 'Paid')], default='', max_length=255),
        ),
    ]
